@extends('layouts.app')

@section('content')
<div class="staticPagesWrapper">
    <div class="container">
        <div class="terms">
            <h2>TERMS OF USE</h2>
            <h3>Introduction and Definitions</h3>
            <p>ScoutMee, a Delaware CCorporation (d/b/a, and referred to herein as, “ScoutMee”), operates this website to provide online booking and promotional tools for performers, eventrelated service providers, music tutors, music schools, musicians, agents, consumers, talent promoters, event planners, and entertainment buyers of all types. In these Website Terms of Use, the words “you” and “your” refer to any person accessing or using the Site, and the words “we”, “us”, and “our” refer to ScoutMee.</p>
            <p>To assist you in using our www.scoutmee.com website, including all subdomains thereof (collectively, the “Site”), and to ensure a clear understanding of the relationship arising from your use of our Site, we have created these Terms of Use. Together, these Terms of Use and our <a href="/privacy">Privacy Policy</a> govern your use of this Site, so please read them both carefully.</p>
            <p>By using or otherwise accessing our Site, you are acknowledging that: (a) you have read and understood these Terms of Use, and (b) you unconditionally agree to comply with, and be legally bound by, these Terms of Use as they exist on the date of each such use or access. If you disagree with any of these Terms of Use in any way, please leave this Site now. If you have any questions or need any clarifications, please <a href="/contact_us">contact us</a> before using the Site.</p>

            <h3>Relationship and Conduct</h3>
            <p>1. Incorporation of Introduction. You hereby represent that everything in the Introduction, above, is true and accurate, and agree that the Introduction is a part of these Terms of Use.</p>
            <p>2. Modification of Terms of Use. We may modify these Terms of Use at any time. Any such modifications will apply prospectively, from the date the modifications are made, as designated by the “Last Revised” date depicted above. Your use of the Site subsequent to any modifications will constitute acceptance of the Terms of Use as so changed. You will be given notice of each modification by: (a) the updating of the “Last Revised” date, above, and (b) an email sent to you by us at the address you designate , in the event you choose to designate an email address . If you choose not to designate an email address , you expressly agree that, by updating the “Last Revised” date when modifications are made, we are providing you with sufficient notice of such modifications, and that you will therefore be bound thereby if you continue to use the Site. As such, please check the “Last Revised” date prior to each use of the Site by you, as you will be bound by these Terms of Use as they exist on the date of each such use.</p>
            <p>3. Reserved Rights. Without limitation to all other rights enjoyed by ScoutMee, we expressly reserve the right at any time to:</p>
            <ol>
                <li><span>Modify these Terms of Use as provided herein;</span></li>
                <li><span>Change the Site, including eliminating or discontinuing any content on or feature of the Site, and/or adding new features, categories, business models, offerings;</span></li>
                <li><span>Terminate the membership of any Member without refund and/or pursue legal action against any user of this website who does not comply with these Terms of Use, though ScoutMee assumes no obligation to do the same;</span></li>
                <li><span>Change any fees or charges for using the Site;</span></li>
                <li><span>Change, edit, add to, disable or delete any Profile information or imagery at our sole discretion, or other Site content, without notice;</span></li>
                <li><span>Terminate “Music Lovers” accounts we feel may be putting our Members at risk, either because they have not provided a valid phone number or because of suspicions we may have regarding the validity of an inquiry;</span></li>
                <li><span>Revoke any account without refund for acting in a manner ScoutMee deems inappropriate or unprofessional during any aspect of membertoclient or membertomember interaction, including without limitation: initial contact, booking negotiation, performance or service provision, and settlement of payment due; and</span></li>
                <li><span>Remove any free Member account at any time for any reason.</span></li>
            </ol>
            <p>4. Online Conduct. At all times when using or accessing this Site, you agree that:</p>
            <ol>
                <li><span>You are solely responsible for the content or information you publish or display (hereinafter, “post”) on the Site or transmit to other Members.</span></li>
                <li><span>You will not post on the Site, or transmit to other Members or ScoutMee employees, any defamatory, inaccurate, abusive, obscene, profane, offensive sexually oriented, threatening, harassing, racially offensive, or illegal material, or any material that infringes or violates another party’s rights (including, but not limited to, intellectual property rights, and rights of privacy and publicity). Please <a href="/contact_us">contact us</a> in writing if you believe any material contained in the Site does not comply with the foregoing.</span></li>
                <li><span>You will use the Site in a manner consistent with any and all applicable laws and regulations.</span></li>
                <li><span>You will not include in your profile any offensive or sexually suggestive references or post any photographs or other images containing nudity. ScoutMee.com reserves the right, but has no obligation, to remove without warning or refund any profile or photograph or image that does not comply with these prohibitions.</span></li>
                <li><span>You will maintain current contact information on your profile, including at least one main image. We reserve the right to add any image or edit any information at any time.</span></li>
                <li><span>You will not falsify your identity or misrepresent yourself in any way on the Site or in your ScoutMee profile.</span></li>
                <li><span>You will not “stalk” or otherwise harass any person in any way.</span></li>
                <li><span>You will not engage in advertising to, or solicitation of, other Members to buy or sell any products or services through the Site.</span></li>
                <li><span>You will not transmit any chain letters, spam or junk email to other Members or to us.</span></li>
                <li><span>You will not express or imply that any statements you make are endorsed by us, without our specific prior written consent.</span></li>
                <li><span>You will not harvest or collect personal information about other Members whether or not for commercial purposes, without our written consent.</span></li>
                <li><span>You will not use any robot, spider, site search/retrieval application, or other manual or automatic device or process to retrieve, index, “data mine”, “scrape” or in any way reproduce or circumvent the navigational structure or presentation of the Site or its contents.</span></li>
                <li><span>You will not post, distribute or reproduce in any way any copyrighted material, trademarks, or other proprietary information without obtaining the prior consent of the owner of such proprietary rights. As a Member it is your obligation to determine affiliation of songs you upload to the Site or link to your profile. Apart from these affiliations we do not have permission to post music from other artists on the Site and you agree that by uploading your music you have unrestricted permission to post such music. For a list of ASCAP and BMI artists, please contact ASCAP and BMI directly.</span></li>
                <li><span>You will not interfere with or disrupt our services or the Site, or the servers or networks connected to our services or the Site.</span></li>
                <li><span>You will not post html code except where instructed in any area of your profile on this Site.</span></li>
                <li><span>You will not post, email or otherwise transmit any material that contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any software, hardware or telecommunications equipment.</span></li>
                <li><span>You hereby grant ScoutMee permission to add content to your Profile at our sole discretion by uploading content found on the website link that you post as your “Official Website” in order to increase the quality or presentation of your Profile.</span></li>
                <li><span>You will not forge headers or otherwise manipulate identifiers in order to disguise the origin of any information transmitted through the Service.</span></li>
                <li><span>You will not “frame” or “mirror” any part of the Site, without our prior written authorization. You also shall not use meta tags or code or other devices containing any reference to www.scoutmee.com or our services or the Site in order to direct any person to any other website for any purpose.</span></li>
                <li><span>You will not modify, adapt, sublicense, translate, sell, reverse engineer, decipher, decompile or otherwise disassemble any portion of the Site or any software used on or for the Site or cause others to do so.</span></li>
                <li><span>You are solely responsible for your interactions with other Members. ScoutMee reserves the right, but has no obligation, to monitor disputes between you and other Members.</span></li>
                <li><span>You will not, for any reason, directly or indirectly submit reviews to a Profile with which you are affiliated. Reviews may only be posted by actual clients who have booked you. You may dispute any review you feel to be fraudulent, but the removal of reviews is solely at our discretion. Also, writing reviews for your competitors with the intent of tearing them down is the lowest form of competitive behavior and will result in immediate termination of your account without refund if we have reason to believe you have done so. As a company we follow the “Golden Rule” and require the same from our Members: treat others the way you wish to be treated. Posting any illegitimate reviews will result in termination of your ScoutMee membership without refund, and we may forever bar you from the Site.</span></li>
                <li><span>You will not resell or reoffer any lead you receive through ScoutMee to another performer, vendor or service provider, nor will you reoffer or post to any website any lead you receive through your relationship with this website.</span></li>
                <li><span>You will respond fully, truthfully, and within three (3) business days to any request for information or other inquiry from ScoutMee related to your or another Member’s compliance with these Terms.</span></li>
            </ol>
            <p>Failure to comply with these provisions outlined under “Online Conduct” may result in immediate suspension or termination of your right to use the Site without refunding your membership fees. ScoutMee reserves the right, in its sole discretion and in all instances, to determine whether a Member has or has not complied with any provision contained in these Terms.</p>
            <p>5. Registration and Membership of Users. While you can visit our Site, and review a range of information about musicians and music teachers, as well as other materials relating to the entertainment industry, without registering, to post information on our Site, and to obtain access to certain other materials or information from our Site, we may ask that you become a registered user to access certain information. Our registration forms will specify the information which you must provide in order to enjoy the particular feature, and the information which you may, at your option, choose to provide or withhold. In connection with registering at our Site, you agree to provide us with accurate, complete, and updated information required by the registration form (“Registration Data”), including, without limitation, your legal name, address, telephone number(s), applicable payment data (e.g., credit card number and expiration date) and such other information that may be required by such forms. Information provided to us by you in connection with registering at our Site will be protected by us in accordance with the terms of our Privacy Policy.</p>
            <p>All financial information addressed on the site (including membership fees, vendor balances, vendor deposits, service fees and/or any other various pricing information) is given in terms of US dollars. All sales are final and will not be refunded, unless specifically agreed to otherwise by us.</p>
            <p>When you register at our Site, you will create a password and a user id, which will provide you access to certain services and materials available through the Site unless revoked by us for any reason. You agree not to disclose your user id and password to any third party. If at any time you believe that your user id name and/or password has been revealed to any other party, or otherwise compromised, you agree to notify us in writing immediately and to change your login name and/or password immediately through the member control panel on our Site. You agree to be responsible for and to indemnify, defend and hold ScoutMee, and its officers, directors, employees, agents, licensors, and suppliers, harmless from any injury, loss or damage we incur on account of any unauthorized use of your login name or password. YOU ARE SOLELY RESPONSIBLE FOR MAINTAINING THE CONFIDENTIALITY OF YOUR USERNAME AND PASSWORD AND FOR ANY AND ALL ACTIVITIES THAT ARE CONDUCTED THROUGH YOUR ACCOUNT.</p>
            <p>6. Under age user policy. In order to use ScoutMee you must be at least 18 years of age, or the legal age to form a binding contract in your jurisdiction if that age is greater than 18 years of age. Individuals who are under the age of 18 or the legal age to form a binding contract in their jurisdiction (“Minors”) are prohibited from registering for and/or booking talent on this website.</p>
            <p>A legal guardian of a Minor may create a profile for a Minor, and must specify so at the time of registration. However, the legal guardian is responsible for everything done with that account. You represent that the information that you provide about yourself as requested in any account registration form on ScoutMee is accurate and complete.</p>
            <p>7. Free Member Accounts. ScoutMee allows Members to set up one (1) free account, which may be terminated or redacted by ScoutMee at any time, for any reason, and without notice. Members shall not have more than one free Profile for themselves and one for their Band act, if any.</p>
            <p>8. Links To Other Websites And Services. ScoutMee does not control the availability or content of any outside websites, services, or resources to which this Site may link.</p>
            <p>Concerns regarding any such service, resource, or link should be directed to the particular outside service or resource. Unless stated otherwise, ScoutMee does not endorse, sanction, or verify sites to which our Site links, and we provide these links merely for our users’ convenience. Access to such other sites is at your own risk, and we disclaim all liability with regard to your access to such linked websites. In addition, we do not endorse, sanction, or verify sites that link to this Site, even if any logo or mark of ScoutMee is used as part of the link to this Site.</p>
            <p>9. Disclaimer. The contents of our Site, and the Site as a whole, is intended strictly for the purposes of: (i) providing a forum for performers, bands, music teachers, musicians and other talent to post information about themselves, and (ii) facilitating the booking of such talent for engagements (collectively, “Permitted Uses”). You represent and warrant that you understand, and agree, that ScoutMee is not, will not be, and will not in any way be construed to be a party to any contract or agreement between any users of this Site regarding the provisions of services at any event or engagement. While we do believe that ScoutMee Members will achieve some amount of exposure from a listing on the Site, we do not guarantee in any way that the use of the Site will produce paying clients for our members. We do not represent or guarantee that this Site will further the careers of our Members, help them financially or otherwise produce income. Failure to receive the outcome you expected does not warrant a refund of payment. Furthermore, ScoutMee does not take responsibility for the content of any Member profile, or Member services offered on any profile. Concerns regarding any such service, resource, or link posted or offered by a Member should be directed to the particular Member. ScoutMee does not endorse, sanction, or verify Members on this website. Contacting these Members, whether through our services or separately is at your own risk, and we disclaim all liability with regard to your dealings with any Member listed on this Site.</p>
            <p>10. No Partnership, Agency, or Affiliation. Unless stated otherwise by ScoutMee, it is expressly understood that ScoutMee is not the partner, agent, joint venturer, or otherwise an affiliate of you or any user of the Site.</p>

            <h3>Intellectual Property Rights and Complaints</h3>
            <p>11. Site Content Ownership. Unless otherwise noted, all copyrighted works, trademarks, service marks, trade dress, or other intellectual properties depicted in any texts, images, illustrations, designs, icons, photographs, video clips, sound clips, or and other materials on the Site (collectively, the “Contents”) are owned, licensed by, used with permission, or otherwise lawfully used by ScoutMee. The Site as a whole is protected by copyright and trade dress, all worldwide right, title and interest in and to which is owned by ScoutMee. Unless otherwise noted, by using a third party’s trademark or trade name on this Site, ScoutMee does not intend to suggest any affiliation with or endorsement of such third party or its products or services, and ScoutMee hereby expressly disclaims any such affiliation or endorsement.</p>
            <p>You may download and copy the Contents displayed on the Site solely for personal use, and provided that you do not remove any copyright or other proprietary notices contained on the materials. No right, title, or interest in any downloaded materials or software is transferred to you as a result of any such downloading or copying. You may not reproduce, modify, publish, distribute, sell, or exploit in any way, in whole or in part, any of the Contents or the Site. Use of the Contents or any related software which is not expressly permitted by these Terms of Use constitutes a breach of these Terms of Use, and may also constitute a violation of copyright, trademark, and other applicable laws.</p>
            <p>12. License to Submissions. With respect to any photographs, designs, images, video clips, sound clips, or other media files you may provide to ScoutMee for posting on your PromoKit (collectively, “Submissions”), such Submissions shall remain your property.</p>
            <p>You hereby unconditionally grant to ScoutMee a nonexclusive, irrevocable and royaltyfree license to use, reproduce, publicly perform and publicly display, the Submissions SOLELY IN CONNECTION WITH THE SITE, SCOUTMEE'S PUBLIC SOCIAL PROFILES AND SCOUTMEE'S YOUTUBE CHANNEL, where users' videos will be categorized and played in playlists.</p>
            <p>ScoutMee does not endorse, sanction or verify, and specifically disclaims responsibility or liability for, any user profiles. You represent, warrant and agree (i) that you are authorized to submit the Submissions you provide to us and to license the same to us as set forth above; and (ii) that all Submissions submitted by you to the Site does not and will not violate any rights of any third party, including, without limitation, copyright, trademark, privacy or other personal or proprietary right(s). You agree to keep a copy of any content you provide, as ScoutMee shall have no obligation to return any content to you should it become damaged or lost.</p>
            <p>13. Disclosures by Scoutmee. Without limiting any of the foregoing, you agree that ScoutMee may use or disclose information about your act and your use of the Site in accordance with our <a href="/privacy">Privacy Policy</a> , which is incorporated by reference herein. With respect to any information relating to other users of the Site to which you may be permitted access through the Site, you agree that you may use such information only in connection with activities related to the purpose of the Site, which activities, without limitation, shall not include (i) the sending of unsolicited communications of a commercial nature; (ii) the sending of any other communications after receiving notification that the recipient no longer wishes to receive communications from you; or (iii) the sale or rental of such personal information to any other parties.</p>
            <p>14. Complaints Over Perceived Infringement. ScoutMee respects intellectual property rights, and will terminate registered users and deny access to others who, in our discretion, infringe the intellectual property rights of others.</p>
            <p>If you believe that materials posted on our Site infringe rights you enjoy under copyright law in specific materials (a “Work”), we request that you follow the procedure described below to notify us of your concerns or objections. In turn, we agree to respond to your notice, as outlined below, and ultimately remove or disable access to material that is finally found to infringe your Work.</p>
            <p>15. DMCA Designated Agent and Takedown Procedures. If you believe materials posted on our Site or related social profiles and channels infringe any copyright interest in a Work you created or own, you must direct your concerns to our agent, designated under the Digital Millennium Copyright Act (“DMCA”) to respond to such concerns:</p>
            <p><br><em>ScoutMee CCorp</em></p>
            <p><br><em>Attn: Matteo Daste, DMCA Designated Agent</em></p>
            <p>Squire Patton Boggs (US) LLP<br>600 Hansen Way<br>Palo Alto, California 94304<br>M +1 415 321 9499<br>Skype matteosf<br><em>Matteo.Daste@squirepb.com</em> |<br>squirepattonboggs.com</p>
            <p><br>The DMCA documents the Notice and Takedown Procedure steps to be followed when we receive a complaint from a putative copyright holder or agent of a copyright holder, hereafter referred to as the “Complainant”. If you believe any usergenerated content on our Site infringes your copyright, you must submit (by email or physical mail) to our designated DMCA Agent a DMCA Copyright Infringement Notice which complies with the following:</p>
            <ol>
                <li><span>A physical or electronic signature of the Complainant;</span></li>
                <li><span>An identification of the infringed copyrighted work, or, if multiple copyrighted works are covered by a single notification, a list of all works alleged to have been infringed;</span></li>
                <li><span>An identification of the alleged infringing material and information reasonably sufficient to permit us to locate the material;</span></li>
                <li><span>Contact information of the Complainant, such as an address, telephone number, electronic mail address;</span></li>
                <li><span>A statement that the Complainant has a good faith belief that use of the material in the manner complained of is not authorized by the copyright owner, its agent, or the law; and</span></li>
                <li><span>A statement that the information contained in the notification is accurate, and under penalty of perjury, that the Complainant is authorized to act on behalf of the copyright owner.</span></li>
            </ol>
            <p>If the notice is deemed valid, then we will proceed with the takedown procedure set forth in the DMCA.</p>

            <h3>Disputes, Liabilities, and Disclaimers</h3>
            <p>16. Disclaimer of All Warranties. All data and information featured on this Site is provided strictly “asis”, without any WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF TITLE, ACCURACY, truth, reliability, COMPLETENESS, CURRENCY, NONINFRINGEMENT, OR ANY IMPLIED WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Further, we specifically make no representation or warranty REGARDING, and WE assume no liability or responsibility REGARDING: (i) the QUALITY or availability of any postings made by you or any other users of the Site; (II) whether any SCHEDULED events OR ENGAGEMENTS WILL OCCUR; (III) whether PERSONS OR ACTS contacted through the Site will appear at any events OR ENGAGEMENTS; (iV) the ability of you or any other user of the Site to engage in transactions with any other user of the Site; (V) any details relating to any transactions you may engage in with any other use of the Site; (VI) the quality of the listings or other information offered by you or any user of the Site; (vII) the financial condition of you or any user of the Site; or (vIIi) compliance with local, state and federal laws by you or any other user of the Site. ScoutMee makes no representation that the information in the Site is appropriate or available for use in locations outside the United States, and access to this Site from locations where the provision of such information may be illegal is prohibited. Users who determine to access this Site from such locations do so on their own initiative and are responsible for compliance with all applicable local laws.</p>
            <p>17. Limitation of Liability. NEITHER GigSalad NOR ANY PERSON OR ENTITY AFFILIATED OR INVOLVED WITH CREATING, PRODUCING, HOSTING, MAINTAINING OR DELIVERING THE SITE SHALL BE LIABLE FOR ANY DIRECT, INCIDENTAL, CONSEQUENTIAL, SPECIAL, INDIRECT, OR PUNITIVE DAMAGES ARISING OUT OF YOUR, OR ANY OTHER PARTY’S ACCESS TO OR USE OF THE SITE. TO MAXIMUM EXTENT ALLOWED BY APPLICABLE LAW, SCOUTMEE SHALL HAVE NO LIABILITY OR RESPONSIBILITY FOR ANY ERRORS, OMISSIONS, OR INACCURACIES IN THE CONTENT ON THE SITE OR INFORMATION FLOWING THROUGH THE SITE.</p>
            <p>18. Assumption of Risk. YOUR USE AND BROWSING OF THE SITE IS AT YOUR RISK. YOU SHOULD CONDUCT YOUR OWN INDEPENDENT INVESTIGATION OF THE USERS OF THIS SITE BEFORE ENTERING INTO ANY TRANSACTION WITH SUCH PERSONS. IN NO EVENT SHALL WE OR ANY OTHER PARTY INVOLVED IN CREATING, PRODUCING, OR DELIVERING THE SITE BE LIABLE FOR ANY FINANCIAL OR OTHER OBLIGATIONS THAT MAY ARISE BETWEEN YOU AND ANY OTHER USER OF THE SITE.</p>
            <p>You acknowledge that documents posted to and Content available at the Site may contain computer viruses AND YOU EXPRESSLY ASSUME THAT RISK. Should you download any such materials from the Site, IT IS YOUR RESPONSIBILITY TO PERFORM ANY SCANNING OR OTHER ANTIVIRUS PRECAUTIONS AS YOU DEEM NECESSARY. UNDER NO CIRCUMSTANCES WILL WE BE RESPONSIBLE FOR ANY LOSS OR DAMAGE CAUSED BY ANY MATERIALS DOWNLOADED FROM THE SITE.</p>
            <p>YOU ACKNOWLEDGE THAT YOUR USE OF THE SITE IS AT YOUR SOLE RISK, AND AGREE TO VERIFY ANY INFORMATION BEFORE RELYING UPON IT. YOU ASSUME FULL RESPONSIBILITY FOR ALL COSTS ASSOCIATED WITH ALL NECESSARY SERVICING OR REPAIRS OF ANY EQUIPMENT YOU USE IN CONNECTION WITH YOUR USE OF OUR SITE.</p>
            <p>19. Waiver and release. By using this Site, you hereby waive any rights of recovery, under any theory of law, that you may have against GigSalad, and its parents, subsidiaries and affiliates, and you release GigSalad from any claim, cause of action or demand, on account of your use of the Site or the provision of the Site by GigSalad.</p>
            <p>20. Indemnification. By using the Site, you agree to indemnify, defend, save and hold harmless ScoutMee, and its officers, directors, employees, agents, licensors, affiliates, parents, subsidiaries, subcontractors and suppliers against any loss, damage, cost or expenses arising out of or in connection with your use of this Site or any breach by you of these Terms of Use or any representation or warranty made herein.</p>
            <p>21. Applicable Law. These Terms of Use will be governed by, and construed and enforced in accordance with, the laws of the State of California, excepting conflict of laws provisions thereof.</p>
            <p>22. Exclusive Jurisdiction. You and ScoutMee further agree that any action to enforce these Terms of Use must be brought in the state or federal courts of California.</p>
            <p>23. Enforcement Costs. Should either of us employ an attorney or attorneys to enforce any the provision(s) of these Terms of Use, the nonprevailing party in any final judgment agrees to pay the prevailing party’s reasonable expenses, including attorneys’ fees and expenses, incurred in connection with such enforcement action and efforts, as determined by a court of competent jurisdiction.</p>

            <h3>Miscellaneous</h3>
            <p>24. Site and Service Modifications. We may make improvements or other changes to the Site, or to the information and services offered at the Site, without notice to you. We may add, delete, move, or modify some or all of the Site at any time.</p>
            <p>25. Transfer of Rights and Assignment. ScoutMee may wish at some point to assign or transfer its rights in this Site to a third party. You agree that ScoutMee may transfer or assign to a third party all of its rights and obligations with respect to you, including any rights and obligations with respect to your Personally Identifiable Information, on the condition that such third party agree to abide by a privacy policy at least as protective as ScoutMee’s thenapplicable Privacy Policy.</p>
            <p>26. Severability. Invalidation of any provision of these Terms of Use shall not impair or affect in any manner the validity and enforceability of the remaining portions, which in such event shall remain in full force and effect as if such invalid provision had never been included herein.</p>
            <p>27. Captions. The captions herein are inserted only as a matter of convenience and in no way define, limit, describe or otherwise affect the scope or interpretation of this Agreement.</p>
        </div>
        <!-- terms -->
    </div>
    <!-- container -->
</div>
<!-- staticPagesWrapper -->
@endsection
