branch-defaults:
  dev:
    environment: scoutmee-dev
  master:
    environment: scoutmee-prod
global:
  application_name: ScoutMee
  default_ec2_keyname: prod-key
  default_platform: 64bit Amazon Linux 2015.09 v2.0.6 running PHP 5.6
  default_region: us-west-2
  profile: eb-cli
  sc: git
container_commands:
 01migrate:
    command: "php artisan migrate"
    leader_only: true
 # 02seed:
 #    command: "php artisan db:seed"
 #    leader_only: true
