@include('mail.partial.header')<!-- START HEIGHT SPACE 20PX LAYOUT-1 --><tbody><tr><td valign="top" align="center" style="background-color:#ecebeb;">
            <table width="600" height="20" align="center" border="0" cellspacing="0" cellpadding="0" style="min-width: 600px; width: 600px; background-color: #ffffff;mso-table-lspace:0pt; mso-table-rspace:0pt;" class="full-width"><tbody><tr><td valign="top" height="20" width="20" style="width: 20px; height: 20px; line-height: 20px; font-size: 20px;">
                <img src="{{ asset('assets/images/mail/space.png') }}" width="20" alt="space" style="display:block; max-height:20px; max-width:20px;"></td>
              </tr></tbody></table></td>
        </tr><!-- END HEIGHT SPACE 20PX LAYOUT-1--></tbody><!-- START HEIGHT SPACE 20PX LAYOUT-1 --><tbody><tr><td valign="top" align="center" style="background-color:#ecebeb;">
            <table width="600" height="20" align="center" border="0" cellspacing="0" cellpadding="0" style="min-width: 600px; width: 600px; background-color: #ffffff;mso-table-lspace:0pt; mso-table-rspace:0pt;" class="full-width"><tbody><tr><td valign="top" height="20" width="20" style="width: 20px; height: 20px; line-height: 20px; font-size: 20px;">
                <img src="{{ asset('assets/images/mail/space.png') }}" width="20" alt="space" style="max-height: 20px; max-width: 20px; display: block;"></td>
              </tr></tbody></table></td>
        </tr><!-- END HEIGHT SPACE 20PX LAYOUT-1--></tbody><!-- START LAYOUT-1/1 --><tbody><tr><td align="center" valign="top" style="background-color:#ecebeb;">
            <!-- start  container width 600px -->
            <table width="600" align="center" border="0" cellspacing="0" cellpadding="0" class="container" style="padding-left: 20px; padding-right: 20px; min-width: 600px; width: 600px; background-color: #ffffff;mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td valign="top">
                  <!-- start container width 560px -->
                  <table width="560" align="center" border="0" cellspacing="0" cellpadding="0" class="full-width" style="width: 560px;mso-table-lspace:0pt; mso-table-rspace:0pt;"><!-- start text content --><tbody><tr><td valign="top">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td valign="top" width="auto" align="center">
                              <!-- start button -->
                              <table border="0" align="center" cellpadding="0" cellspacing="0" width="auto" style="mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td width="auto" align="center" valign="middle" height="28" style="border: 1px solid rgb(236, 236, 237); font-size: 18px; font-family: Roboto, Arial, Helvetica, sans-serif; text-align: center; color: rgb(163, 162, 162); font-weight: 300; padding-left: 18px; padding-right: 18px; word-break: break-word; line-height: 26px; background-clip: padding-box;"><span style="text-decoration: underline; font-size: 18px; line-height: 26px;"><span style="color: rgb(163, 162, 162); font-weight: bold; font-size: 18px; line-height: 26px;"><a href="#" style="color: rgb(208, 93, 104); font-size: inherit; border-style: none; text-decoration: none !important; line-height: 26px;" data-mce-href="#" border="0">THANKS FOR SIGNING UP!</a></span></span></td>
                                </tr></tbody></table><!-- end button --></td>
                          </tr></tbody></table></td>
                    </tr><!-- end text content --></tbody></table><!-- end  container width 560px --></td>
              </tr></tbody></table><!-- end  container width 600px --></td>
        </tr><!-- END LAYOUT-1/1 --></tbody><!-- START LAYOUT-1/2 --><tbody><tr><td align="center" valign="top" style="background-color:#ecebeb;">
            <!-- start  container width 600px -->
            <table width="600" align="center" border="0" cellspacing="0" cellpadding="0" class="container" style="padding-left: 20px; padding-right: 20px; min-width: 600px; width: 600px; background-color: #ffffff;mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td valign="top">
                  <!-- start container width 560px -->
                  <table width="560" align="center" border="0" cellspacing="0" cellpadding="0" class="full-width" style="width: 560px;mso-table-lspace:0pt; mso-table-rspace:0pt;"><!-- start text content --><tbody><tr><td valign="top">
                        <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt; mso-table-rspace:0pt;"><!-- start text content --><tbody><tr dup="0"><td valign="top">
                              <table width="100%" border="0" cellspacing="0" cellpadding="0" align="center" style="mso-table-lspace:0pt; mso-table-rspace:0pt;"><!--start space height --><tbody><tr><td height="15" style="border-collapse: collapse; height: 15px; line-height: 15px; font-size: 15px;"></td>
                                </tr><!--end space height --><tr><td style="font-size: 13px; font-family: Roboto, Arial, Helvetica, Arial; color: rgb(163, 162, 162); font-weight: 300; text-align: center; word-break: break-word; line-height: 21px;"><span style="font-size: 13px; line-height: 21px;">Whether&nbsp;you're looking for a DJ&nbsp;for your wedding, a jazz trio for your dinner&nbsp;party, or a guitar teacher to impress your friends… WE'RE HERE&nbsp;FOR YOU!<br><br>Try using our <a href="http://www.scoutmee.com/search?search=&amp;location=&amp;latitude=&amp;longitude=" data-mce-href="http://www.scoutmee.com/search?search=&amp;location=&amp;latitude=&amp;longitude=" style="font-size: inherit; border-style: none; text-decoration: none !important; line-height: 21px;" border="0">Search</a>&nbsp;function if you already know what you are looking for, or click on the '<span style="font-style: italic; font-size: 13px; line-height: 21px;">Get&nbsp;Cool Ideas</span>' button for some inspiration.<br><br><br><span style="text-decoration: underline; font-size: 13px; line-height: 21px;"><span style="font-weight: bold; font-size: 13px; line-height: 21px;">PRO TIPS</span></span>:</span><br><ul><li style="text-align: left;"><span style="font-size: 13px; line-height: 21px;"><span style="font-size: 13px; line-height: 21px;">Don't forget to check out our&nbsp;</span><a href="https://www.youtube.com/channel/UCXTldWhFZp5xpQ_2wu2MBcA/about" data-mce-href="https://www.youtube.com/channel/UCXTldWhFZp5xpQ_2wu2MBcA/about" style="font-size: inherit; border-style: none; text-decoration: none !important; line-height: 21px;" border="0">YouTube channel</a><span style="font-size: 13px; line-height: 21px;">&nbsp;for the latest uploads!</span><br></span></li><li style="text-align: left;"><span style="font-size: 13px; line-height: 21px;"><span style="font-size: 13px; line-height: 21px;">Set the search criteria, browse through the hottest profiles and follow those you like the most! You'll receive updates every time they upload a new song, video, event or social post!</span></span></li><li style="text-align: left;"><span style="font-size: 13px; line-height: 21px;"><span style="font-size: 13px; line-height: 21px;">You can also contact the artists you like most, and book&nbsp;them for your own Live Performance and/or Music Lessons!</span><br><br><br>We can't wait to see you discover your next favorite artist on our platform. It's your turn&nbsp;to be a Talent Scout! :)</span></li></ul><br></td>
                                </tr><!--start space height --><tr><td height="15" style="border-collapse: collapse; height: 15px; line-height: 15px; font-size: 15px;"></td>
                                </tr><!--end space height --></tbody></table></td>
                          </tr><!-- end text content --><tr><td valign="top" width="100%" align="center">
                              <!-- start button -->
                              <table width="auto" border="0" align="center" cellpadding="0" cellspacing="0" style="margin:0 auto;mso-table-lspace:0pt; mso-table-rspace:0pt;"><tbody><tr><td valign="top">
                                    </td>
                                </tr></tbody></table><!-- end button --></td>
                          </tr></tbody></table></td>
                    </tr><!-- end text content --><!--start space height --><tr><td height="20" style="border-collapse: collapse; height: 20px; line-height: 20px; font-size: 20px;"></td>
                    </tr><!--end space height --></tbody></table><!-- end  container width 560px --></td>
              </tr></tbody></table><!-- end  container width 600px --></td>
        </tr><!-- END LAYOUT-1/2 --></tbody>
        @include('mail.partial.footer')